class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedListIterator:
    def __init__(self, head):
        self.current = head

    def __iter__(self):
        return self

    def __next__(self):
        if self.current is None:
            raise StopIteration
        data = self.current.data
        self.current = self.current.next
        return data

class LinkedList:
    def __init__(self):
        self.head = None
        self._size = 0

    def append(self, data):
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
        else:
            current = self.head
            while current.next is not None:
                current = current.next
            current.next = new_node
        self._size += 1

    def remove(self, condition):
        current = self.head
        prev = None
        while current is not None:
            if condition(current.data):
                if prev is None:
                    self.head = current.next
                else:
                    prev.next = current.next
                self._size -= 1
                return True
            prev = current
            current = current.next
        return False

    def find(self, condition):
        current = self.head
        while current is not None:
            if condition(current.data):
                return current.data
            current = current.next
        return None
        
    def find_all(self, condition):
        result = LinkedList()
        current = self.head
        while current is not None:
            if condition(current.data):
                result.append(current.data)
            current = current.next
        return result

    def get_at(self, index):
        if index < 0 or index >= self._size:
            return None
        current = self.head
        # Not using range or for-loop, using a manual while loop to avoid any potential built-in lists generated by range in older pythons (though range is a generator in python 3, this is strictly safe)
        i = 0
        while i < index:
            current = current.next
            i += 1
        return current.data

    def size(self):
        return self._size

    def is_empty(self):
        return self._size == 0

    def clear(self):
        self.head = None
        self._size = 0

    def __iter__(self):
        return LinkedListIterator(self.head)
